### ISSUE TITLE
对现有文档的3个小建议

### ISSUE THREAD

**Issue by chenhengjie123** [alibaba/jvm-sandbox-repeater#1]
您好，我是来自 ppmoney 的测试开发同学。

最近通过阿里技术的公众号推送了解到了这个工具，也第一时间进行了试用。从介绍、试用和一些源码阅读中，感受到这个工具的强大之处，非常感谢阿里能开源这样一个工具！

而在试用的过程中，感受到目前官方提供文档有不少的小问题，用起来不是太流畅。因此根据我个人的一些感受，提一些小的建议：

> 1、部分超链接404
> 
> 如 <https://github.com/alibaba/jvm-sandbox-repeater/blob/master/docs/user-guide-cn.md> 中的 `Slogan Demo究竟发生了什么`、`RepeaterConfig.java` 等，点击后都是 404 。建议修正下。
> 
> 2、json 配置项没有说清楚是放在哪里的。
> 
> 官方文档中给出的位置只是源码目录的位置，且链接 404 。经过自行试验，可以生效的配置项位置为 `~/.sandbox-module/cfg/repeater-config.json` 。但这明显不满足多项目使用不同配置文件的需要，应该不是正确解答。建议补充下。
> 
> 3、缺少应用到自己的应用时，回放方面的说明
> 
> 对于自行设置被测应用这个章节，只提到了录制怎么做，没提到回放怎么做，有点懵逼。期望可以详细说明下回放怎么做。

最后，期望这个工具能越来越好。

PS：尝鲜的详细记录我记录在了 testerhome 社区，如果有兴趣可以移步 [jvm-sandbox-repeater 尝鲜记录 (持续更新)](https://testerhome.com/topics/19778) ，也非常欢迎提出您的宝贵意见建议。

**Comment by zhaoyb1990** [comment]
@chenhengjie123   非常感谢试用和建议，文档和链接问题我们已悉数修复，关于用户使用文档，非常抱歉提供了这么糟糕的用户体验。

> 针对 -> 2、json 配置项没有说清楚是放在哪里的。

针对这个问题，静态配置文件只是用于单机使用，方便快速使用，如果需要项目工程级使用，需要通过服务端下发配置，模块有预留接口，详情看文档更新

> 针对 -> 3、缺少应用到自己的应用时，回放方面的说明

回放部分文档已简单更新，具体可通过[RecordFacadeApi](https://github.com/alibaba/jvm-sandbox-repeater/blob/master/repeater-console/repeater-console-start/src/main/java/com/alibaba/repeater/console/start/controller/RecordFacadeApi.java)顺藤摸瓜全部弄清楚


文档更新的比较慢，但是整体代码功能基本都已全面，后续更新完整体录制回放的架构图和jvm-sandbox-repeater所处的位置就会更加明确
