### ISSUE TITLE
javaRepeater执行回放时，使用getType判断InvokeType是否相等，实际内存地址不一样，导致回放抛出类型不一致的异常

### ISSUE THREAD

**Issue by wentiegang** [alibaba/jvm-sandbox-repeater#10]
1、com.alibaba.jvm.sandbox.repeater.plugin.java.JavaRepeater第38行
![image](https://user-images.githubusercontent.com/10055262/62530092-7ded5880-b872-11e9-8640-3ca33034cc91.png)

2、使用getType().name()判断实际回放类型为Java
![image](https://user-images.githubusercontent.com/10055262/62530253-c3118a80-b872-11e9-8205-1d63ac513f8b.png)
![image](https://user-images.githubusercontent.com/10055262/62530267-cb69c580-b872-11e9-8352-4f58901630a0.png)

ps：以下为实际执行结果
![image](https://user-images.githubusercontent.com/10055262/62530519-4d59ee80-b873-11e9-87fb-75aeecf64226.png)

**Comment by ElesG** [comment]
是的，这个要么把源码改成取name重新打包，要么等官方发布一个invokeType的是枚举的版本。
详情可以看看：
https://github.com/alibaba/jvm-sandbox-repeater/pull/2

**Comment by zhaoyb1990** [comment]
本身InvokeType是一个枚举，考虑到以后插件编写是新增枚举要修改api新增，不好扩展，所以设计成了接口；

develop20190829-分支上修复了这类问题；
