### ISSUE TITLE
develop20190829-分支发布计划

### ISSUE THREAD

**Issue by zhaoyb1990** [alibaba/jvm-sandbox-repeater#15]
最新dev分支[develop20190829](https://github.com/alibaba/jvm-sandbox-repeater/tree/develop20190829)，已Fix了issue里面大部分问题；#13 #14 #9 #10 问题；

关于本次发布的计划包括：

- redis 插件适配 (原计划7月底-)
- dubbo 回放支持
- bug fix
- ...

大家可以使用情况，讨论下有什么新需求

> 关于PR的提交，目前有几个PR还没有Agree，原因是PR对问题的解法目前不是最优，没有彻底的解决问题，针对的问题也在本次Dev分支中有解决，大家可以参考一下，也希望大家积极的贡献idea和使用场景

**Comment by ElesG** [comment]
求调用外部http接口的录制和mock方案，直接把okhttp3的方法mock会有问题~
https://github.com/alibaba/jvm-sandbox-repeater/issues/17
