### ISSUE TITLE
无法录制实现了javax.servlet.Filter接口的类下面的filter方法

### ISSUE THREAD

**Issue by Tuyuantao** [alibaba/jvm-sandbox-repeater#16]

**Comment by zhaoyb1990** [comment]
HTTP录制回放是基于javax.servlet.http.HttpServlet#service方法实现，跟filter无关。

如果是自定义servlet，不走HttpServlet确实可能无法录制

**Comment by Tuyuantao** [comment]
不是自定义的servlet，controller的相关方法都能录制到，但是在controller外面包的过滤器方法却不能录制到。
