### ISSUE TITLE
在线推送配置更新优化

### ISSUE THREAD

**Issue by cdwcdw2** [alibaba/jvm-sandbox-repeater#170]
![image](https://user-images.githubusercontent.com/10495045/165006897-8d779d76-adf7-4e88-bc0d-fe3eae12534d.png)

图中代码应该调整为，先比较，再赋值新的配置

**Comment by Mengleijin** [comment]
@cdwcdw2 你好，想问一下在线推送配置有什么作用？只是推送classPattern，methodPatterns，includeSubClasses这三个参数吗？

**Comment by cdwcdw2** [comment]
> @cdwcdw2 你好，想问一下在线推送配置有什么作用？只是推送classPattern，methodPatterns，includeSubClasses这三个参数吗？

修改了配置，可以立刻推送到app端，立刻生效，其它配置也可以推送，插件变更不能推送
