### ISSUE TITLE
uncaught exception occurred when execute mock strategy, type=PARAMETER_MATCH java.lang.NullPointerException: null

### ISSUE THREAD

**Issue by dknebula** [alibaba/jvm-sandbox-repeater#19]
![image](https://user-images.githubusercontent.com/7954364/64164892-969f5d00-ce76-11e9-8fa0-eb60c5142c25.png)

**Comment by zhaoyb1990** [comment]
[develop20190829](https://github.com/alibaba/jvm-sandbox-repeater/tree/develop20190829) 中已修复该问题
