### ISSUE TITLE
repeater在console模式下如何配置应用名和环境

### ISSUE THREAD

**Issue by shutdowner** [alibaba/jvm-sandbox-repeater#194]
如题，目前console收集到的流量数据这两个值都是unknown，大佬们如有知晓烦请告知，不胜感激！

**Comment by Aresxue** [comment]
-Dapp.env=local -Dapp.name=repeater-demo，在挂载agent的应用上加上这两个jvm参数

**Comment by shutdowner** [comment]
经验证 成功了 多谢大佬！！！
