### ISSUE TITLE
java调用回放时反序列化失败

### ISSUE THREAD

**Issue by xjwldlover** [alibaba/jvm-sandbox-repeater#20]
1.在进行java调用时，录制成功，并可以获取到序列化信息，如截图
![image](https://user-images.githubusercontent.com/12861199/64258507-f6baff80-cf59-11e9-9fdb-6d79b5de91d7.png)

2，回放时能请求到服务，并读取到序列化信息
![image](https://user-images.githubusercontent.com/12861199/64258576-1520fb00-cf5a-11e9-9201-3b048a3da389.png)
3，（问题）在回放反序列化时报空指针，请问是什么原因导致的，有什么解决办法？
![image](https://user-images.githubusercontent.com/12861199/64258753-5f09e100-cf5a-11e9-862d-e4d7ac264ffb.png)

![image](https://user-images.githubusercontent.com/12861199/64258659-37b31400-cf5a-11e9-846e-531f17997e48.png)

**Comment by xjwldlover** [comment]
录制和回放时的invocation对象不一样，不知道是否有关系，为什么会不一样
![image](https://user-images.githubusercontent.com/12861199/64260409-62eb3280-cf5d-11e9-9834-9826bee7ef06.png)
![image](https://user-images.githubusercontent.com/12861199/64260508-91690d80-cf5d-11e9-896b-bd75fa1ef9b2.png)

**Comment by xjwldlover** [comment]
上一个是回放，下图是录制

**Comment by zhaoyb1990** [comment]
信息不太全，不能定位问题。

解答几个疑惑，invocation没有重写toString方法，每次生成的对象不一致，是正常的。

自己先确认一下拦截点的入参和返回值是否都可被序列化

针对这个问题，可以把saveRepeat的base64值拿出来看下，才能分析原因

**Comment by infra-qa** [comment]
一样遇到上述问题3，用录制出来的信息可以反序列化出RecordWrapper，但是不能反序列化出RepeatModel，报NPE异常。怎么解？

**Comment by zhaoyb1990** [comment]
未能提供更多有效信息，无法复现，暂时先关闭

**Comment by ydzhao-reyes** [comment]
public void scroll(ScrollRequest scrollRequest, HttpServletRequest request, HttpServletResponse response) ，对这种类型的方法就会序列化失败
