### ISSUE TITLE
开启ttl进行录制时 ClassCastException异常 

### ISSUE THREAD

**Issue by dknebula** [alibaba/jvm-sandbox-repeater#21]
> java.lang.ClassCastException: com.alibaba.ttl.TtlRunnable cannot be cast to java.util.concurrent.Callable

![image](https://user-images.githubusercontent.com/7954364/64329584-17d72b00-d002-11e9-91b0-4dbbb424ff3c.png)

> 应该根据参数声明类型来转换,而不是根据实参类型

![image](https://user-images.githubusercontent.com/7954364/64330956-84ebc000-d004-11e9-87c5-38959d24b26c.png)

**Comment by zhaoyb1990** [comment]
不太能理解，实际参数类型和声明类型理论基类是一致的，换成声明类型就没问题了吗？（我理解如果按你的分析实际参数类型是Runnable声明类型是Callable，那么报错会发生在`TtlCallable.get((Callable)parameterArray[0])`

针对这个错误异常，`TtlRunnable.get((Runnable)parameterArray[0])`既然已经生效，说明此处的`parameterArray[0]`确实是一个`Runnable`，那么即使没有启用ttl，这个也会有强转异常。

**Comment by dknebula** [comment]
> 不太能理解，实际参数类型和声明类型理论基类是一致的，换成声明类型就没问题了吗？（我理解如果按你的分析实际参数类型是Runnable声明类型是Callable，那么报错会发生在`TtlCallable.get((Callable)parameterArray[0])`
> 
> 针对这个错误异常，`TtlRunnable.get((Runnable)parameterArray[0])`既然已经生效，说明此处的`parameterArray[0]`确实是一个`Runnable`，那么即使没有启用ttl，这个也会有强转异常。


parameterArray[0] instanceOf Runnable
parameterArray[0] instanceOf Callable
都是True的情况会报错


SomeTask someTask = ...

// someTask 既是Callable, 也是Runnable
assert someTask instanceOf Callable
assert someTask instanceOf Runnable

// 用强转, 显式声明调用    ExecutorService.submit(Callable<T> task)
executorService.submit((Callable) someTask);  // repeater会报错

**Comment by zhaoyb1990** [comment]
OK，了解了，目前这种写法确实有问题，未考虑到同时实现两个的情况，有空的话帮忙提个PR。谢谢。

**Comment by zhaoyb1990** [comment]
Merged
