### ISSUE TITLE
插件开发：hibernate的update方法及mybatis-plus部分版本的部分方法没有返回值，怎么设置拦截点呢

### ISSUE THREAD

**Issue by sourireling** [alibaba/jvm-sandbox-repeater#225]
![image](https://github.com/alibaba/jvm-sandbox-repeater/assets/40731443/e9f2cf8f-e219-48ba-8d92-21cf45fd7e09)
hibernate的update方法没有返回值，实际业务场景这个方法抛出了异常，而mock的时候是正常的，跟实际情况不一致

**Comment by Aresxue** [comment]
拦截点和有没有返回值理论上没有关系。
