### ISSUE TITLE
Double-Checked Locking

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [alibaba/jvm-sandbox-repeater#28]
https://github.com/alibaba/jvm-sandbox-repeater/blob/49109b3ee67be28bb0c7d89b183bf9aa334f52e1/repeater-plugin-core/src/main/java/com/alibaba/jvm/sandbox/repeater/plugin/core/spring/SpringContextAdapter.java#L97-L106
Double-Checked Locking is widely cited and used as an efficient method for implementing lazy initialization in a multithreaded environment.
Unfortunately, it will not work reliably in a platform independent way when implemented in Java, without additional synchronization.
declares the springContainerClass field volatile offers a much more elegant solution

**Comment by zhaoyb1990** [comment]
Thank you very much for pointing out the wrong implementation of the code.

We have implemented a more elegant version based on your suggestion and will commit later.

**Comment by zhaoyb1990** [comment]
#42 fixed in this commit
