### ISSUE TITLE
ResultSet类型的响应反序列化失败

### ISSUE THREAD

**Issue by yongshenga33** [alibaba/jvm-sandbox-repeater#31]
我对mysql的executeQuery方法进行了监控配置，方法返回的响应是ResultSet类型。ResultSet类型的响应反序列化失败，报[Error-1002]-hessian-deserialize-erroe的错。

**Comment by zhaoyb1990** [comment]
并不是所有的东西都可以序列化，ResultSet是无法 被序列化话的，所以切面的选择很重要，一般建议选择拦截点的请求入参和返回值都是简单对象
