### ISSUE TITLE
dubbo类型入口流量录制

### ISSUE THREAD

**Issue by carmina-most** [alibaba/jvm-sandbox-repeater#36]
dubbo类型的入口流量 ，入口配置是怎么配置的？现在还是不支持dubbo入口的流量进行回放吗？dubbo接口子调用又是怎么配置的？

**Comment by zhaoyb1990** [comment]
dubbo的入口流量(provider)/子调用(consumer)录制，不要额外配置，repeater-config.json里面的默认配置已支持。

**Comment by zhaoyb1990** [comment]
Merged Into Master

**Comment by carmina-most** [comment]
非常感谢，master分支看到了dubbo repeater的回放支持，赞
