### ISSUE TITLE
应用挂载了repeater，并且开启ttl的情况下，每执行一次ThreadPoolExecutor 的submit、execute方法，某些类的实例会不断的增加，gc时都回收不掉

### ISSUE THREAD

**Issue by Benjar** [alibaba/jvm-sandbox-repeater#41]
### bug描述
应用挂载了repeater，并且开启ttl的情况下，每执行一次ThreadPoolExecutor 的submit、execute方法，以下一些类的实例都会不断的增加，在系统执行ygc、甚至fgc之后都不会释放

java.util.concurrent.FutureTask
com.alibaba.ttl.TtlRunnable
com.alibaba.jvm.sandbox.api.listener.ext.Advice
com.alibaba.jvm.sandbox.api.listener.ext.AdviceAdapterListener.WrapAdvice

### 

### demo代码 
```java

@Controller
@RequestMapping("/foo")
public class FooController {

    private static ThreadPoolExecutor EXECUTOR = new ThreadPoolExecutor(4, 4,
            0L, TimeUnit.SECONDS, new LinkedBlockingQueue<>(1024),
            new BasicThreadFactory.Builder().namingPattern("common-pool-%d").build());


    @RequestMapping(value = "/test", method = RequestMethod.GET)
    @ResponseBody
    public String submit(@RequestParam("count") int count) {
        for (int i = 0; i < count; i++) {
            EXECUTOR.submit(() -> {
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss.SSS");
                System.out.println(Thread.currentThread().getName() + " submitted at " + sdf.format(new Date()));
            });
        }
        return "submit OK " + new Date();
    }
}
```

### repeater-congfig配置

```json
{
  "degrade": false,
  "exceptionThreshold": 1000,
  "httpEntrancePatterns": [
   
  ],
  "javaEntranceBehaviors": [
    
  ],
  "javaSubInvokeBehaviors": [
    
  ],
  "pluginIdentities": [
    "http",
    "java-entrance",
    "java-subInvoke",
    "mybatis",
    "ibatis",
    "dubbo-provider",
    "dubbo-consumer"
  ],
  "repeatIdentities": [
    "java",
    "http",
    "dubbo"
  ],
  "sampleRate": 10000,
  "useTtl": true
}
```

#### 应用挂载repeater
应用启动之后，将sandbox、repeater插件挂载到应用进程上

![截图_9edaab04-52e3-47f1-9c26-87bda7e85844](https://user-images.githubusercontent.com/8326387/69812335-e8177800-122a-11ea-9312-932d334b5286.png)

![image](https://user-images.githubusercontent.com/8326387/69812454-201ebb00-122b-11ea-9a8e-fc0f0a9821fd.png)

#### 应用不挂载repeater

应用启动之后，不挂载repeater
![截图_7430af08-5223-4606-b00f-7f7585b9933d](https://user-images.githubusercontent.com/8326387/69812469-27de5f80-122b-11ea-8f4e-567c9ec175b6.png)

**Comment by Benjar** [comment]
简单的排查一下，大概的原因如下。详细的问题原因还需要作者自己去复现、深入排查
![image](https://user-images.githubusercontent.com/8326387/69853221-337c6580-12c1-11ea-8213-47d2a10073a0.png)

**Comment by zhaoyb1990** [comment]
非常感谢，该问题最终定位原因跟您定位的一致；

由于AdviceListener只订阅了Before事件，导致stack无法pop，并且一致持有引用，导致内存泄露

问题已修复，稍后会发布。

这个问题比较严重，错误也很低级

**Comment by zhaoyb1990** [comment]
已修复
