### ISSUE TITLE
使用tomcat部署的应用，dubbo回放失败

### ISSUE THREAD

**Issue by lvzeting** [alibaba/jvm-sandbox-repeater#45]
跟踪发现，是泛化调用的时候，proxy类用的是当前类加载器，然后dubbo相关的类我， 又配置了rount到应用的加载器
response":{
        "@type":"java.lang.IllegalArgumentException",
        "localizedMessage":"interface com.alibaba.dubbo.rpc.service.GenericService is not visible from class loader",
        "message":"interface com.alibaba.dubbo.rpc.service.GenericService is not visible from class loader",
        "stackTrace":[
            {
                "className":"com.alibaba.dubbo.common.bytecode.Proxy",
                "fileName":"Proxy.java",
                "lineNumber":96,
                "methodName":"getProxy",
                "nativeMethod":false
            },
            {
                "className":"com.alibaba.dubbo.common.bytecode.Proxy",
                "fileName":"Proxy.java",
                "lineNumber":69,
                "methodName":"getProxy",
                "nativeMethod":false
            },
            {
                "className":"com.alibaba.dubbo.rpc.proxy.javassist.JavassistProxyFactory",
                "fileName":"JavassistProxyFactory.java",
                "lineNumber":35,
                "methodName":"getProxy",
                "nativeMethod":false
            },
            {
                "className":"com.alibaba.dubbo.rpc.proxy.AbstractProxyFactory",
                "fileName":"AbstractProxyFactory.java",
                "lineNumber":64,
                "methodName":"getProxy",
                "nativeMethod":false
            },
            {
                "className":"com.alibaba.dubbo.rpc.proxy.AbstractProxyFactory",
                "fileName":"AbstractProxyFactory.java",
                "lineNumber":34,
                "methodName":"getProxy",
                "nativeMethod":false
            },
            {
                "className":"com.alibaba.dubbo.rpc.proxy.wrapper.StubProxyFactoryWrapper",
                "fileName":"StubProxyFactoryWrapper.java",
                "lineNumber":65,
                "methodName":"getProxy",
                "nativeMethod":false
            },
            {
                "className":"com.alibaba.dubbo.rpc.ProxyFactory$Adaptive",
                "fileName":"ProxyFactory$Adaptive.java",
                "lineNumber":-1,
                "methodName":"getProxy",
                "nativeMethod":false
            },
            {
                "className":"com.alibaba.dubbo.config.ReferenceConfig",
                "fileName":"ReferenceConfig.java",
                "lineNumber":432,
                "methodName":"createProxy",
                "nativeMethod":false
            },
            {
                "className":"com.alibaba.dubbo.config.ReferenceConfig",
                "fileName":"ReferenceConfig.java",
                "lineNumber":335,
                "methodName":"init",
                "nativeMethod":false
            },
            {
                "className":"com.alibaba.dubbo.config.ReferenceConfig",
                "fileName":"ReferenceConfig.java",
                "lineNumber":164,
                "methodName":"get",
                "nativeMethod":false
            },
            {
                "className":"com.alibaba.jvm.sandbox.repeater.plugin.dubbo.DubboRepeater",
                "fileName":"DubboRepeater.java",
                "lineNumber":70,
                "methodName":"executeRepeat",
                "nativeMethod":false
            },
            {
                "className":"com.alibaba.jvm.sandbox.repeater.plugin.core.impl.AbstractRepeater",
                "fileName":"AbstractRepeater.java",
                "lineNumber":47,
                "methodName":"repeat",
                "nativeMethod":false
            },
            {
                "className":"com.alibaba.jvm.sandbox.repeater.plugin.core.impl.api.DefaultFlowDispatcher",
                "fileName":"DefaultFlowDispatcher.java",
                "lineNumber":43,
                "methodName":"dispatch",
                "nativeMethod":false
            },
            {
                "className":"com.alibaba.jvm.sandbox.repeater.plugin.core.impl.spi.RepeatSubscribeSupporter",
                "fileName":"RepeatSubscribeSupporter.java",
                "lineNumber":64,
                "methodName":"onSubscribe",
                "nativeMethod":false
            },
            {
                "className":"sun.reflect.NativeMethodAccessorImpl",
                "fileName":"NativeMethodAccessorImpl.java",
                "lineNumber":-2,
                "methodName":"invoke0",
                "nativeMethod":true
            },
            {
                "className":"sun.reflect.NativeMethodAccessorImpl",
                "fileName":"NativeMethodAccessorImpl.java",
                "lineNumber":62,
                "methodName":"invoke",
                "nativeMethod":false
            },
            {
                "className":"sun.reflect.DelegatingMethodAccessorImpl",
                "fileName":"DelegatingMethodAccessorImpl.java",
                "lineNumber":43,
                "methodName":"invoke",
                "nativeMethod":false
            },
            {
                "className":"java.lang.reflect.Method",
                "fileName":"Method.java",
                "lineNumber":498,
                "methodName":"invoke",
                "nativeMethod":false
            },
            {
                "className":"com.google.common.eventbus.Subscriber",
                "fileName":"Subscriber.java",
                "lineNumber":95,
                "methodName":"invokeSubscriberMethod",
                "nativeMethod":false
            },
            {
                "className":"com.google.common.eventbus.Subscriber$1",
                "fileName":"Subscriber.java",
                "lineNumber":80,
                "methodName":"run",
                "nativeMethod":false
            },
            {
                "className":"com.alibaba.ttl.TtlRunnable",
                "fileName":"TtlRunnable.java",
                "lineNumber":51,
                "methodName":"run",
                "nativeMethod":false
            },
            {
                "className":"java.util.concurrent.ThreadPoolExecutor",
                "fileName":"ThreadPoolExecutor.java",
                "lineNumber":1142,
                "methodName":"runWorker",
                "nativeMethod":false
            },
            {
                "className":"java.util.concurrent.ThreadPoolExecutor$Worker",
                "fileName":"ThreadPoolExecutor.java",
                "lineNumber":617,
                "methodName":"run",
                "nativeMethod":false
            },
            {
                "className":"java.lang.Thread",
                "fileName":"Thread.java",
                "lineNumber":745,
                "methodName":"run",
                "nativeMethod":false
            }
        ]
    },

**Comment by zhaoyb1990** [comment]
确认是bug，在发起调用之前，没有切换当前线程的classloader，导致底层一些使用当前线程类加载器进行类加载时会出现错误。

**Comment by zhaoyb1990** [comment]
已修复
