### ISSUE TITLE
attach 到引用了 spring-boot-starter-actuator的项目会导致进程crash！！！！

### ISSUE THREAD

**Issue by handsometang** [alibaba/jvm-sandbox-repeater#46]
错误类 WebMvcMetricsFilter!  详情请查看进程crash日志  hs_err_pid{pid}.log

**Comment by zhaoyb1990** [comment]
麻烦提供更详细堆栈， 或者更详细版本信息。


本地测试工程引入spring-boot-starter-actuator 1.4.7-RELEASE   attach没有出现crash

**Comment by handsometang** [comment]
sandbox version :1.2.1
spring-boot version: 2.0.4

**Comment by zhaoyb1990** [comment]
无法复现，如果crash确认是sandbox attach后导致，麻烦提供一下关键信息。
