### ISSUE TITLE
加载http插件错误是为什么？

### ISSUE THREAD

**Issue by d545229548** [alibaba/jvm-sandbox-repeater#47]
![image](https://user-images.githubusercontent.com/23092674/72160927-25f6e700-33fa-11ea-96b3-019c79150c54.png)
抛了上面代码这个异常，加载的应用 springmvc工程打的war包，放在tomcat执行的

**Comment by zhaoyb1990** [comment]
请问是使用agent还是attach模式。

报这个错的原因是目标classloader中未找到servlet-api相关的类，如果是agent启动，可以把等待时间加长，  不过一般不建议大家通过agent启动

**Comment by sawyer1379416087** [comment]
我试 attach 模式启动，也出现了这个问题。请问怎么解决的呢

**Comment by sawyer1379416087** [comment]
> 请问是使用agent还是attach模式。
> 
> 报这个错的原因是目标classloader中未找到servlet-api相关的类，如果是agent启动，可以把等待时间加长， 不过一般不建议大家通过agent启动


我attach 启动也有这个问题，请问怎么可以避免呢
