### ISSUE TITLE
sandbox对系统性能影响

### ISSUE THREAD

**Issue by Tuyuantao** [alibaba/jvm-sandbox-repeater#6]
在使用之前，调研了下性能，发现sanbox-repeater记录会对系统产生很大的影响
![image](https://user-images.githubusercontent.com/4477056/62099084-8ddbca00-b2bf-11e9-8185-cdf8b016233f.png)

**Comment by zhaoyb1990** [comment]
请问这是什么系统指标，sandbox attach会重新加载类，瞬间比较占用cpu资源是预期内的。

**Comment by Tuyuantao** [comment]
http接口调用指标，看了下应该是序列化数据太多导致的，后面调了下采样率，就不会出现这种情况了。

**Comment by LuVsLu** [comment]
如果依赖接口太多确实序列化很占系统资源，能减少一些序列化的次数吗？我看到每次录制子调用都有一次及时序列化动作，这个动作能省去吗？
`   
 /**
     * 及时序列化
     *
     * @param invocation 调用信息
     */
    public static void inTimeSerialize(Invocation invocation) throws SerializeException {
        if (invocation.getResponse() != null && invocation.getResponseSerialized() == null) {
            invocation.setResponseSerialized(provider.provide(Serializer.Type.HESSIAN)
                    .serialize2String(invocation.getResponse(), invocation.getClassLoader()));
        }
        if (invocation.getRequest() != null && invocation.getRequestSerialized() == null) {
            invocation.setRequestSerialized(provider.provide(Serializer.Type.HESSIAN)
                    .serialize2String(invocation.getRequest(), invocation.getClassLoader()));
        }
        if (invocation.getThrowable() != null && invocation.getThrowableSerialized() == null) {
            invocation.setThrowableSerialized(provider.provide(Serializer.Type.HESSIAN)
                    .serialize2String(invocation.getThrowable(), invocation.getClassLoader()));
        }
    }
`
