### ISSUE TITLE
对Okhttp会有mock插件支持吗 #

### ISSUE THREAD

**Issue by shiyuanxiu** [alibaba/jvm-sandbox-repeater#81]
想问下对Okhttp会有mock插件支持吗 #

**Comment by wuguanyu** [comment]
@shiyuanxiu 感觉这个 okHttp 录制上应该就有问题

**Comment by wuguanyu** [comment]
针对 buffer 和 stream 无法序列化的问题

**Comment by zhaoyb1990** [comment]
https://github.com/alibaba/jvm-sandbox-repeater/tree/develop20210614  已有支持，可以尝试使用下
