### ISSUE TITLE
回放示例中的getRegress(String name, int count)方法报错，找不到对应的方法

### ISSUE THREAD

**Issue by wentiegang** [alibaba/jvm-sandbox-repeater#9]
1、需要的录制方法，第二个参数为int
![image](https://user-images.githubusercontent.com/10055262/62463560-eaa61b80-b7bc-11e9-88b4-2f8dafbba5c5.png)

2、com.alibaba.jvm.sandbox.repeater.plugin.core.impl.api.DefaultEventListener组装invocation使用beforeEvent，argumentArray第二个参数变成Java.lang.Integer
![image](https://user-images.githubusercontent.com/10055262/62463623-0e696180-b7bd-11e9-9298-1cdc88165237.png)

3、com.alibaba.jvm.sandbox.repeater.plugin.java.JavaRepeater回放时找不到对应方法，报错
![image](https://user-images.githubusercontent.com/10055262/62464018-17a6fe00-b7be-11e9-982a-4c3af554411a.png)

**Comment by zhaoyb1990** [comment]
预期内问题，这个case也是专门预留测试的，可以看JavaRepeater里面有注释

**Comment by wentiegang** [comment]
请问后续的一个修复方案是什么？在jvm-sandbox拦截before事件event里参数由原来int已经变成java.lang.Integer了，需要jvm-sandbox修复这个问题吗？

**Comment by zhaoyb1990** [comment]
develop20190829-分支修复；方案是利用java原生的签名解析入参
