### ISSUE TITLE
There is a vulnerability in  fastjson-alibaba 1.2.67,upgrade recommended

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [alibaba/jvm-sandbox-repeater#95]
https://github.com/alibaba/jvm-sandbox-repeater/blob/0a1b47b2aae295a5c4627e533e7da94b9ed2b14d/pom.xml#L19

Recommended upgrade version：
1.2.68.sec10

**Comment by zhaoyb1990** [comment]
upgraded
