### ISSUE TITLE
关于repeatId的获取

### ISSUE THREAD

**Issue by conansoft** [alibaba/jvm-sandbox-repeater#98]
请问一下，日志里拿到traceId以后，触发回访的接口http://127.0.0.1:8001/facade/api/record，需要在header里传参repeatId，请问这个repeatId从哪里获取？不胜感激！

**Comment by zhaoyb1990** [comment]
触发回放的RepeatId是可选的，如果不指定会自动生成，主动指定是为了在发起回放之后，可以查询回放结果
